[2024-12-23T09:01:16.541+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_workflow.fetch_rating_data manual__2024-12-23T08:56:28.503318+00:00 [queued]>
[2024-12-23T09:01:16.559+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_workflow.fetch_rating_data manual__2024-12-23T08:56:28.503318+00:00 [queued]>
[2024-12-23T09:01:16.560+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-23T09:01:16.587+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): fetch_rating_data> on 2024-12-23 08:56:28.503318+00:00
[2024-12-23T09:01:16.591+0000] {standard_task_runner.py:57} INFO - Started process 1701 to run task
[2024-12-23T09:01:16.596+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_workflow', 'fetch_rating_data', 'manual__2024-12-23T08:56:28.503318+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmphqhyuif6']
[2024-12-23T09:01:16.598+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask fetch_rating_data
[2024-12-23T09:01:16.629+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T09:01:16.694+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_workflow.fetch_rating_data manual__2024-12-23T08:56:28.503318+00:00 [running]> on host 6e594a6ef2a4
[2024-12-23T09:01:16.807+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_workflow' AIRFLOW_CTX_TASK_ID='fetch_rating_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T08:56:28.503318+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T08:56:28.503318+00:00'
[2024-12-23T09:01:16.809+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T09:01:16.810+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/extract/API_rating_Themoviedb.py']
[2024-12-23T09:01:16.822+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T09:02:17.526+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-23T09:02:17.556+0000] {process_utils.py:131} INFO - Sending 15 to group 1701. PIDs of all processes in the group: [1702, 1701]
[2024-12-23T09:02:17.558+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1701
[2024-12-23T09:02:17.568+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-23T09:02:17.573+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-12-23T09:02:17.650+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-23T09:02:17.665+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_data_workflow, task_id=fetch_rating_data, execution_date=20241223T085628, start_date=20241223T090116, end_date=20241223T090217
[2024-12-23T09:02:17.686+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task fetch_rating_data (Task received SIGTERM signal; 1701)
[2024-12-23T09:02:17.723+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1702, status='terminated', started='09:01:16') (1702) terminated with exit code None
[2024-12-23T09:02:17.731+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1701, status='terminated', exitcode=1, started='09:01:15') (1701) terminated with exit code 1
