[2024-12-24T04:07:07.553+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_etl_workflow.fetch_rating_data manual__2024-12-24T04:07:05.974980+00:00 [queued]>
[2024-12-24T04:07:07.566+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_etl_workflow.fetch_rating_data manual__2024-12-24T04:07:05.974980+00:00 [queued]>
[2024-12-24T04:07:07.566+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-24T04:07:07.582+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): fetch_rating_data> on 2024-12-24 04:07:05.974980+00:00
[2024-12-24T04:07:07.588+0000] {standard_task_runner.py:57} INFO - Started process 65 to run task
[2024-12-24T04:07:07.591+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_etl_workflow', 'fetch_rating_data', 'manual__2024-12-24T04:07:05.974980+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmp8ocl18l5']
[2024-12-24T04:07:07.593+0000] {standard_task_runner.py:85} INFO - Job 181: Subtask fetch_rating_data
[2024-12-24T04:07:07.614+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-24T04:07:07.660+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_etl_workflow.fetch_rating_data manual__2024-12-24T04:07:05.974980+00:00 [running]> on host ab04c198d044
[2024-12-24T04:07:07.757+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_etl_workflow' AIRFLOW_CTX_TASK_ID='fetch_rating_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T04:07:05.974980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T04:07:05.974980+00:00'
[2024-12-24T04:07:07.759+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-24T04:07:07.760+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/extract/API_rating_Themoviedb.py']
[2024-12-24T04:07:07.774+0000] {subprocess.py:86} INFO - Output:
[2024-12-24T04:07:39.441+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-24T04:07:39.456+0000] {process_utils.py:131} INFO - Sending 15 to group 65. PIDs of all processes in the group: [66, 65]
[2024-12-24T04:07:39.459+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 65
[2024-12-24T04:07:39.490+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-24T04:07:39.491+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-12-24T04:07:39.545+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-24T04:07:39.559+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_data_etl_workflow, task_id=fetch_rating_data, execution_date=20241224T040705, start_date=20241224T040707, end_date=20241224T040739
[2024-12-24T04:07:39.593+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 181 for task fetch_rating_data (Task received SIGTERM signal; 65)
[2024-12-24T04:07:39.648+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=65, status='terminated', exitcode=1, started='04:07:07') (65) terminated with exit code 1
[2024-12-24T04:07:39.650+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=66, status='terminated', started='04:07:07') (66) terminated with exit code None
[2024-12-24T04:07:39.655+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2024-12-24T04:07:39.740+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-24T04:07:41.216+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
