[2024-12-23T08:03:09.864+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_workflow.load_to_dw manual__2024-12-23T08:03:08.430361+00:00 [queued]>
[2024-12-23T08:03:09.878+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_workflow.load_to_dw manual__2024-12-23T08:03:08.430361+00:00 [queued]>
[2024-12-23T08:03:09.878+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-23T08:03:09.895+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): load_to_dw> on 2024-12-23 08:03:08.430361+00:00
[2024-12-23T08:03:09.900+0000] {standard_task_runner.py:57} INFO - Started process 166 to run task
[2024-12-23T08:03:09.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_workflow', 'load_to_dw', 'manual__2024-12-23T08:03:08.430361+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmp57e45imj']
[2024-12-23T08:03:09.905+0000] {standard_task_runner.py:85} INFO - Job 38: Subtask load_to_dw
[2024-12-23T08:03:09.925+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T08:03:09.977+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_workflow.load_to_dw manual__2024-12-23T08:03:08.430361+00:00 [running]> on host 023362aefa72
[2024-12-23T08:03:10.088+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_workflow' AIRFLOW_CTX_TASK_ID='load_to_dw' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T08:03:08.430361+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T08:03:08.430361+00:00'
[2024-12-23T08:03:10.090+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T08:03:10.091+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/load/load_moviedf_to_dw.py']
[2024-12-23T08:03:10.103+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T08:03:10.235+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-12-23T08:03:10.235+0000] {subprocess.py:93} INFO -   File "/opt/***/DE_project/ETL/load/load_moviedf_to_dw.py", line 3, in <module>
[2024-12-23T08:03:10.236+0000] {subprocess.py:93} INFO -     import duckdb
[2024-12-23T08:03:10.236+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'duckdb'
[2024-12-23T08:03:10.240+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-23T08:03:10.255+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-23T08:03:10.261+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_data_workflow, task_id=load_to_dw, execution_date=20241223T080308, start_date=20241223T080309, end_date=20241223T080310
[2024-12-23T08:03:10.272+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 38 for task load_to_dw (Bash command failed. The command returned a non-zero exit code 1.; 166)
[2024-12-23T08:03:10.290+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-23T08:03:10.310+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
