[2024-12-23T09:04:57.972+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_etl_workflow.fetch_movie_data manual__2024-12-23T09:04:56.761987+00:00 [queued]>
[2024-12-23T09:04:57.988+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_etl_workflow.fetch_movie_data manual__2024-12-23T09:04:56.761987+00:00 [queued]>
[2024-12-23T09:04:57.989+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-23T09:04:58.015+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): fetch_movie_data> on 2024-12-23 09:04:56.761987+00:00
[2024-12-23T09:04:58.023+0000] {standard_task_runner.py:57} INFO - Started process 61 to run task
[2024-12-23T09:04:58.029+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_etl_workflow', 'fetch_movie_data', 'manual__2024-12-23T09:04:56.761987+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmpjw_nhmdu']
[2024-12-23T09:04:58.032+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask fetch_movie_data
[2024-12-23T09:04:58.058+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T09:04:58.119+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_etl_workflow.fetch_movie_data manual__2024-12-23T09:04:56.761987+00:00 [running]> on host 393cf9a73c28
[2024-12-23T09:04:58.247+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_etl_workflow' AIRFLOW_CTX_TASK_ID='fetch_movie_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T09:04:56.761987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T09:04:56.761987+00:00'
[2024-12-23T09:04:58.249+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T09:04:58.251+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/extract/API_movie_Themoviedb.py']
[2024-12-23T09:04:58.265+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T09:08:03.416+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-23T09:08:03.459+0000] {process_utils.py:131} INFO - Sending 15 to group 61. PIDs of all processes in the group: [63, 61]
[2024-12-23T09:08:03.460+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 61
[2024-12-23T09:08:03.479+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-23T09:08:03.485+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-12-23T09:08:03.546+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-23T09:08:03.570+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_data_etl_workflow, task_id=fetch_movie_data, execution_date=20241223T090456, start_date=20241223T090457, end_date=20241223T090803
[2024-12-23T09:08:03.607+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 58 for task fetch_movie_data (Task received SIGTERM signal; 61)
[2024-12-23T09:08:03.634+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=61, status='terminated', exitcode=1, started='09:04:57') (61) terminated with exit code 1
[2024-12-23T09:08:03.640+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=63, status='terminated', started='09:04:57') (63) terminated with exit code None
[2024-12-23T09:08:03.644+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2024-12-23T09:08:03.739+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T09:08:05.707+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-23T09:08:05.707+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
