[2024-12-24T04:07:02.918+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_etl_workflow.movie_json_to_csv manual__2024-12-24T04:00:13.353591+00:00 [queued]>
[2024-12-24T04:07:02.943+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_etl_workflow.movie_json_to_csv manual__2024-12-24T04:00:13.353591+00:00 [queued]>
[2024-12-24T04:07:02.944+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-24T04:07:02.971+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): movie_json_to_csv> on 2024-12-24 04:00:13.353591+00:00
[2024-12-24T04:07:02.978+0000] {standard_task_runner.py:57} INFO - Started process 55 to run task
[2024-12-24T04:07:02.983+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_etl_workflow', 'movie_json_to_csv', 'manual__2024-12-24T04:00:13.353591+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmp_5zd3qnp']
[2024-12-24T04:07:02.987+0000] {standard_task_runner.py:85} INFO - Job 178: Subtask movie_json_to_csv
[2024-12-24T04:07:03.013+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-24T04:07:03.099+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_etl_workflow.movie_json_to_csv manual__2024-12-24T04:00:13.353591+00:00 [running]> on host ab04c198d044
[2024-12-24T04:07:03.256+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_etl_workflow' AIRFLOW_CTX_TASK_ID='movie_json_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T04:00:13.353591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T04:00:13.353591+00:00'
[2024-12-24T04:07:03.261+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-24T04:07:03.263+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/JSON_to_CSV/JSON_to_CSV_movie.py']
[2024-12-24T04:07:03.280+0000] {subprocess.py:86} INFO - Output:
[2024-12-24T04:07:03.473+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-12-24T04:07:03.474+0000] {subprocess.py:93} INFO -   File "/opt/***/DE_project/JSON_to_CSV/JSON_to_CSV_movie.py", line 7, in <module>
[2024-12-24T04:07:03.481+0000] {subprocess.py:93} INFO -     with open('/opt/***/DE_project/data/JSON/movies_data.json', 'r') as json_file:
[2024-12-24T04:07:03.495+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/opt/***/DE_project/data/JSON/movies_data.json'
[2024-12-24T04:07:03.496+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-24T04:07:03.519+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-24T04:07:03.531+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_data_etl_workflow, task_id=movie_json_to_csv, execution_date=20241224T040013, start_date=20241224T040702, end_date=20241224T040703
[2024-12-24T04:07:03.553+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 178 for task movie_json_to_csv (Bash command failed. The command returned a non-zero exit code 1.; 55)
[2024-12-24T04:07:03.575+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-24T04:07:03.644+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
