[2024-12-23T09:01:55.344+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_workflow.fetch_movie_data manual__2024-12-23T09:01:53.956706+00:00 [queued]>
[2024-12-23T09:01:55.357+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_workflow.fetch_movie_data manual__2024-12-23T09:01:53.956706+00:00 [queued]>
[2024-12-23T09:01:55.357+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-23T09:01:55.376+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): fetch_movie_data> on 2024-12-23 09:01:53.956706+00:00
[2024-12-23T09:01:55.380+0000] {standard_task_runner.py:57} INFO - Started process 1705 to run task
[2024-12-23T09:01:55.385+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_workflow', 'fetch_movie_data', 'manual__2024-12-23T09:01:53.956706+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmputj0np37']
[2024-12-23T09:01:55.386+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask fetch_movie_data
[2024-12-23T09:01:55.407+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T09:01:55.462+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_workflow.fetch_movie_data manual__2024-12-23T09:01:53.956706+00:00 [running]> on host 6e594a6ef2a4
[2024-12-23T09:01:55.583+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_workflow' AIRFLOW_CTX_TASK_ID='fetch_movie_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T09:01:53.956706+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T09:01:53.956706+00:00'
[2024-12-23T09:01:55.584+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T09:01:55.585+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/extract/API_movie_Themoviedb.py']
[2024-12-23T09:01:55.596+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T09:03:20.863+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-23T09:03:20.903+0000] {process_utils.py:131} INFO - Sending 15 to group 1705. PIDs of all processes in the group: [1706, 1705]
[2024-12-23T09:03:20.904+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1705
[2024-12-23T09:03:20.907+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-23T09:03:20.908+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-12-23T09:03:20.978+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-23T09:03:21.004+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_data_workflow, task_id=fetch_movie_data, execution_date=20241223T090153, start_date=20241223T090155, end_date=20241223T090321
[2024-12-23T09:03:21.067+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task fetch_movie_data (Task received SIGTERM signal; 1705)
[2024-12-23T09:03:21.137+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1706, status='terminated', started='09:01:54') (1706) terminated with exit code None
[2024-12-23T09:03:21.141+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1705, status='terminated', exitcode=1, started='09:01:54') (1705) terminated with exit code 1
[2024-12-23T09:03:21.143+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2024-12-23T09:03:21.212+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
