[2024-12-23T08:56:30.037+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_workflow.fetch_movie_data manual__2024-12-23T08:56:28.503318+00:00 [queued]>
[2024-12-23T08:56:30.046+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_workflow.fetch_movie_data manual__2024-12-23T08:56:28.503318+00:00 [queued]>
[2024-12-23T08:56:30.047+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-23T08:56:30.059+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): fetch_movie_data> on 2024-12-23 08:56:28.503318+00:00
[2024-12-23T08:56:30.063+0000] {standard_task_runner.py:57} INFO - Started process 1695 to run task
[2024-12-23T08:56:30.067+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_workflow', 'fetch_movie_data', 'manual__2024-12-23T08:56:28.503318+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmp2j8hm5ml']
[2024-12-23T08:56:30.068+0000] {standard_task_runner.py:85} INFO - Job 48: Subtask fetch_movie_data
[2024-12-23T08:56:30.086+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T08:56:30.127+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_workflow.fetch_movie_data manual__2024-12-23T08:56:28.503318+00:00 [running]> on host 6e594a6ef2a4
[2024-12-23T08:56:30.219+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_workflow' AIRFLOW_CTX_TASK_ID='fetch_movie_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T08:56:28.503318+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T08:56:28.503318+00:00'
[2024-12-23T08:56:30.221+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T08:56:30.222+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/extract/API_movie_Themoviedb.py']
[2024-12-23T08:56:30.233+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T09:00:43.298+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-23T09:00:43.315+0000] {process_utils.py:131} INFO - Sending 15 to group 1695. PIDs of all processes in the group: [1696, 1695]
[2024-12-23T09:00:43.321+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1695
[2024-12-23T09:00:43.322+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-23T09:00:43.322+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-12-23T09:00:43.344+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-23T09:00:43.354+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=movie_data_workflow, task_id=fetch_movie_data, execution_date=20241223T085628, start_date=20241223T085630, end_date=20241223T090043
[2024-12-23T09:00:43.369+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 48 for task fetch_movie_data (Task received SIGTERM signal; 1695)
[2024-12-23T09:00:43.381+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1696, status='terminated', started='08:56:29') (1696) terminated with exit code None
[2024-12-23T09:00:43.383+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1695, status='terminated', exitcode=1, started='08:56:29') (1695) terminated with exit code 1
