[2024-12-23T08:01:22.982+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movie_data_workflow.json_to_csv manual__2024-12-23T07:51:37.452367+00:00 [queued]>
[2024-12-23T08:01:22.996+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movie_data_workflow.json_to_csv manual__2024-12-23T07:51:37.452367+00:00 [queued]>
[2024-12-23T08:01:22.996+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-12-23T08:01:23.014+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): json_to_csv> on 2024-12-23 07:51:37.452367+00:00
[2024-12-23T08:01:23.018+0000] {standard_task_runner.py:57} INFO - Started process 148 to run task
[2024-12-23T08:01:23.022+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movie_data_workflow', 'json_to_csv', 'manual__2024-12-23T07:51:37.452367+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmpyf06t040']
[2024-12-23T08:01:23.023+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask json_to_csv
[2024-12-23T08:01:23.044+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T08:01:23.090+0000] {task_command.py:415} INFO - Running <TaskInstance: movie_data_workflow.json_to_csv manual__2024-12-23T07:51:37.452367+00:00 [running]> on host 023362aefa72
[2024-12-23T08:01:23.193+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='movie_data_workflow' AIRFLOW_CTX_TASK_ID='json_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T07:51:37.452367+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-23T07:51:37.452367+00:00'
[2024-12-23T08:01:23.195+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-23T08:01:23.196+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/JSON_to_CSV/JSON_to_CSV_movie.py']
[2024-12-23T08:01:23.206+0000] {subprocess.py:86} INFO - Output:
[2024-12-23T08:01:23.362+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-12-23T08:01:23.363+0000] {subprocess.py:93} INFO -   File "/opt/***/DE_project/JSON_to_CSV/JSON_to_CSV_movie.py", line 7, in <module>
[2024-12-23T08:01:23.363+0000] {subprocess.py:93} INFO -     with open('/home/diin/HocKi_7/DE_project/data/JSON/movies_data.json', 'r') as json_file:
[2024-12-23T08:01:23.364+0000] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/diin/HocKi_7/DE_project/data/JSON/movies_data.json'
[2024-12-23T08:01:23.368+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-23T08:01:23.383+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-23T08:01:23.391+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=movie_data_workflow, task_id=json_to_csv, execution_date=20241223T075137, start_date=20241223T080122, end_date=20241223T080123
[2024-12-23T08:01:23.405+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task json_to_csv (Bash command failed. The command returned a non-zero exit code 1.; 148)
[2024-12-23T08:01:23.446+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-12-23T08:01:23.477+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
