[2024-12-24T06:12:29.781+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.fetch_movie_data manual__2024-12-24T06:12:28.449758+00:00 [queued]>
[2024-12-24T06:12:29.802+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.fetch_movie_data manual__2024-12-24T06:12:28.449758+00:00 [queued]>
[2024-12-24T06:12:29.803+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-12-24T06:12:29.836+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): fetch_movie_data> on 2024-12-24 06:12:28.449758+00:00
[2024-12-24T06:12:29.842+0000] {standard_task_runner.py:57} INFO - Started process 2030 to run task
[2024-12-24T06:12:29.851+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test', 'fetch_movie_data', 'manual__2024-12-24T06:12:28.449758+00:00', '--job-id', '203', '--raw', '--subdir', 'DAGS_FOLDER/movie_data_workflow.py', '--cfg-path', '/tmp/tmpr8pv_3wo']
[2024-12-24T06:12:29.854+0000] {standard_task_runner.py:85} INFO - Job 203: Subtask fetch_movie_data
[2024-12-24T06:12:29.891+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-24T06:12:29.993+0000] {task_command.py:415} INFO - Running <TaskInstance: test.fetch_movie_data manual__2024-12-24T06:12:28.449758+00:00 [running]> on host 4170f75a0525
[2024-12-24T06:12:30.180+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='diinguyen' AIRFLOW_CTX_DAG_ID='test' AIRFLOW_CTX_TASK_ID='fetch_movie_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T06:12:28.449758+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T06:12:28.449758+00:00'
[2024-12-24T06:12:30.183+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-24T06:12:30.185+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/DE_project/ETL/extract/API_movie_Themoviedb.py']
[2024-12-24T06:12:30.207+0000] {subprocess.py:86} INFO - Output:
[2024-12-24T06:12:49.787+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-24T06:12:49.821+0000] {process_utils.py:131} INFO - Sending 15 to group 2030. PIDs of all processes in the group: [2035, 2030]
[2024-12-24T06:12:49.828+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 2030
[2024-12-24T06:12:49.829+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-24T06:12:49.838+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2024-12-24T06:12:49.934+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 201, in execute
    result = self.subprocess_hook.run_command(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-12-24T06:12:49.972+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=test, task_id=fetch_movie_data, execution_date=20241224T061228, start_date=20241224T061229, end_date=20241224T061249
[2024-12-24T06:12:50.009+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 203 for task fetch_movie_data (Task received SIGTERM signal; 2030)
[2024-12-24T06:12:50.057+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2035, status='terminated', started='06:12:30') (2035) terminated with exit code None
[2024-12-24T06:12:50.064+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2030, status='terminated', exitcode=1, started='06:12:29') (2030) terminated with exit code 1
[2024-12-24T06:12:50.066+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2024-12-24T06:12:50.145+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
